# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7A-wiWXtAVhaWxXG030jaN6_vbxjY9f
"""

import pandas as pd
file_path='/content/Data.xlsx'
df=pd.read_excel(file_path)
df

df = df.drop_duplicates()
df

df = df.drop(columns = "Not_Useful_Column")
df

df["Last_Name"] = df["Last_Name"].str.strip("123._/")
df

df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')

df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','')
df

df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(',',2, expand=True)
df

df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')

df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

df=df.fillna('')
df

for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
        df.drop(x, inplace=True)

df

for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)

df

df = df.reset_index(drop=True)
df